name: build app base

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Why trigger?"
        required: true
        type: string

env:
  IMAGE: "deepflow-app"

jobs:
  build_app_base_amd64:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: docker version
        run: |
          docker version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push deepflow app base builder images
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          file: app/Dockerfile_base
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}:main-base-amd64

  build_app_base_arm64:
    #runs-on: "cirun-aws-arm64-32c--${{ github.run_id }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: docker version
        run: |
          docker version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push deepflow app base builder images
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          file: app/Dockerfile_base
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}:main-base-arm64
